Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.network :private_network, ip: "192.168.99.102"

    config.vm.provider "virtualbox" do |v|
    	v.memory = 2048
	v.cpus = 2
    end

    config.vm.provision "ansible" do |ansible|
      ansible.inventory_path = "inventories/vagrant"
      ansible.verbose = "vvvv"
      ansible.playbook = "main.yml"
      ansible.limit = "all"
    end
end
